### ISSUE TITLE
Feature Request: Schema based Topics

### ISSUE THREAD

**Issue by cmmcleod** [jamesremuscat/EDDN#34]
It would be great if each message schema had its own topic.

A simple map of schema ref to topic:
 - http://schemas.elite-markets.net/eddn/commodity/[Any_Version] -> commodity
 - http://schemas.elite-markets.net/eddn/shipyard/[Any_Version] -> shipyard
 - http://schemas.elite-markets.net/eddn/outfitting/[Any_Version] -> outfitting

The HTTP API would not have to change. I believe all current subscribers are subscribing to ALL, meaning adding topics would not affect them.

I'm writing a service for Coriolis and I have to discard commodity messages at the moment. This is far from a huge issue, but it does use a decent amount of bandwidth since these messages are large and frequent.

Thoughts? :8ball:

**Comment by cmmcleod** [comment]
Looks like the relay is parsing the message and removing the topic if present?

https://github.com/jamesremuscat/EDDN/blob/master/src/eddn/Relay.py#L97

**Comment by AnthorNet** [comment]
Yes the relays can use topics to handle different scheme.
Actually it's not possible while connecting to a relay to use the topic.
One thing you could do is connecting to the gateways and use their topics.

Modifying that behavior on relay will block current clients I think because they should have to remove the topic.
I'm not sure about that but could do some tests when I got some time.

**Comment by cmmcleod** [comment]
Fair enough, I'll look into connecting directly to the gateway

**Comment by jamesremuscat** [comment]
FYI: The design decision here was that relays would be the things that opt into and out of topics, so (for example) clients wishing only to have commodity messages could connect to a commodity-data relay.

Encouraging people to connect directly to the gateways is not necessarily ideal for a number of reasons, but it does seem to be a natural consequence.

@AnthorNet is correct that the implementation of topics as it stands would break all existing clients, since they expect the body of the message to be JSON, not JSON-with-text-prepended ;)

**Comment by cmmcleod** [comment]
No this makes perfect sense, especially from a fan-out perspective.

I didn't know (until I looked into it) how zeroMQ handles topics which is effective while rudimentary.

I don't suppose any is going to host topic specific relays for now, or a relay that keeps topics.  

If you don't want me connecting to the Gateway then I won't :) But if you don't mind, then I will ;)
